name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./CRUD_on_AD
      
    services:
      rabbitmq:
        image: rabbitmq:3.8.9-management
        ports:
         - 5672:5672
         - 15672:15672
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.x
    - name: Build
      if: success()
    # Indien dotnet publish niet werkt dan moet deze stap vervangen worden met 'dotnet build --no-restore'
    # De stap dotnet publish -c Release zal dan moeten verplaatst worden naar 'Run Docker'
      run: dotnet build --no-restore
